label WrongHow1:
  "It was once said that the universe is indifferent to existence of individuals and that their perspectives should not mater....."
  roy "\"What do you mean I don't matter?\""
  "You? You're in the wrong part of the story. Also, how are you even aware of my existence?"
  roy "\"Well here's the thing: I'm CRAZY.....just kinding.....I legit have Aspergers though\""
  "You mean to inform me that autism gives you the ability to see beyond time and space?"
  roy "\"I mean to inform you that I'll be narrating this part of the story....since the player wanted an alternative perspective\""
  roy "\"Although, I am from the future....representation of me Sze remembers reflects who I was prior to character development\""
  "uh........can you at least make sure that you don't do self-inserts? Those things are big cringe"
  roy "\"I don't make promises that I can't keep....however, I will be replacing a few names with placeholders\""
  roy "\"so..here we go: Most people follow linear branches of logic: sometimes their logic curves and sometimes it reflects\""
  roy "\"But in most of these cases, people have their justifications for why they do something before they do these things\""
  roy "\"But suppose there was a person who could not comprehend actions in terms of convetional logic......a person who could not explain the exact reason why they did or were planning to do something when they did it\""
  roy "\"....however, this was a person that would inevitably find enough reason to finish the task they started.\""
  roy "\"In their eyes, their reasons did not matter if in the end, there was nothing to show for from the task.\""
  roy "\"And so with that in mind, here is but a snippet of their story...from a year before the events of Sze's main story\""
  #insert scene of FSHS, beginning of yr10
  "Ok, so having taken over as narrator: here's the situation....so, the person in question is {s}one Eugene{/s} one known as Eugene...."
  ugn "ok....so...another year of high school....once more unto the breach, eh?"
  "But little did he know of what was to come next......"
  tpe "\"Class, I am your PDHPE teacher for this year and here's the plan for what topics we'll be dealing with.\""
  "As the class reads, some blank stares start emerging, with the teacher immediately snatching the opportunity to say:"
  tpe "\"Yup...the first assessment task...as you can see..is BALLROOM DANCING\""
  ugn "\"AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH\""
  "The whole class turns to Eugene and laughs at him and Eugene realises that he was thinking out loud again"
  tpe "\"On thing of note here is that the dancing will be boy-girl-boy-girl.....don't ask me why....it's just how this task was set\""
  tpe "\"The first couple of periods will be used to teach you about the actual dances you're required to do and then the remaining periods before assessment day can be used for practising\""
  tpe "\"We recommend that you find a dance partner early so that you can maximise practise time. We also recommend that you and your partner practise outside of allocated class times as well\""
  "Eugene scanned through the class and realised that there were some new faces and also some missing....specifically, the first person he was certain that he had a crush on"
  ugn "As the end of the year appraoched, I was previously made aware that there was a dance assessment task and I really wanted to be able to work with them so that I could...get to know them better"
  ugn "But it seems that my crush has left the school....now who am I supposed to dance with?"
  #scene change to school gym
