# Declare images below this line, using the image statement.
# eg. image eileen happy = "eileen_happy.png"

image bg disclaimer = "disclaimer.png"
image bg intro = "arthur.jpg"
image bg school = "Fort_Street_High_School_Memorial_Hall.JPG"
image bg physclass = "physclass"
image bg principaldoor = "principalofficedoor"
image bg principaloffice = "principaloffice"
image bg workshop = "Workshop.jpg"
image bg hall = "hall"
image bg hallentrance = "CZ2Yss_UAAAPRqz.jpg"
image bg schoolfront = "91_big.jpg"
image bg rowecorridor = "fortrowecorridor.jpg"
image bg dream = "eoarchean.jpg"
image bg ded = "szeceded.jpg"
image bg field = "fields_by_applesin_mod.jpg"
image bg parisafremov = "parisafremov.jpg"
image bg norton = "NortonSt.png"
image bg toilet = "toilet.png"
image bg d_workshop = "Workshopdark.jpg"
image bg dreamtree = "dreamtree.png"
image bg economics = "economics.png"

#not sure if that's legit spelling, plz check
style window:
    left_padding 150
image side arthur = "arthurside.png"
image willis normal = "willis1.png"
image side willis = "willisside1"
image rusali normal = "rusali"
image side rusali = "rusali_side.png"
image moxham happy = "moxhamhappy"
image moxham unhappy = "moxhamunhappy"
image side moxham = "moxhamside"
image grant normal = "grant"
image pragash normal = "pragashnormal.png"
image pragash shocked = "pragash2.png"
image yang normal = "yang1.png"
image chao normal = "chao2.png"
image chao happy = "chaohappy.png"
image side pragash = "pragash.png"
image side bill = "billthecleaner.png"
image side dean = "deanside.png"
image side chao = "chaoport.png"
image le calculetor = "calculetor.png"
image side le = "lecalc.png"
image side yin = "willyin.png"
image side richard = "rick.png"
image side roy = "RRRROOOOOOOYYYYYYYYYboi.png"
image side gary = "garry.png"
image side todd = "toddside.png"
image side derek = "derkiederkside.png"
