# Declare characters used by this game.
define sze = Character('Sze', friendship=0, color="#FCFCFC", image="arthur")
define rin = Character('Rina', friendship=0, color="#007408", image="serena")
define kok = Character('Willis', friendship=0, color="#666666", image="willis")
define flu = Character('FLUITSIE', friendship=0, color="#FFFFFF", image="fluitsma")
define rus = Character('Rusali', friendship=0, color="#FFFFFF", image="rusali")
define pra = Character('Pragash', friendship=0, color="#FFFFFF", image="pragash")
define dea = Character('Dean', friendship=0, color="#FFFFFF", image="dean")
define wil = Character('Will Yin', friendship=40, color="#ff0000", image="yin")
define wiy = Character('Will Yang', friendship=40, color="#FFFFFF", image="will")
define tod = Character('Todd Treoir', friendship=0, color="#99ff99", image="todd")
define cha = Character('Chao', friendship=0, color="#FFFFFF", image="chao")
define mox = Character('MOXHAM', friendship=0, color="#FFFFFF", image="moxham")
define gra = Character('GRANT', friendship=0, color="#FFFFFF", image="grant")
define dik = Character('Richard', friendship=0, color="#FFFFFF", image="richard")
define drk = Character('Derek', friendship=0, color="#FFFFFF", image="derek")
define jit = Character('Gary', friendship=5, color="#FFFFFF", image="gary")
define lee = Character('Andrew', friendship=0, color="#FFFFFF", image="andrew")
define roy = Character('Roy', friendship=0, color="#FFFFFF", image="roy")
# jenkins
define but = Character('Aradhya', friendship=0, color="#FFFFFF", image="aradhya")
define dng = Character('Steven', friendship=0, color="#FFFFFF", image="steven")
define bil = Character('Bill the Cleaner', friendship=0, color="747D7D", image="bill")
define ale = Character('Le Calculetor', friendship=0, color="#FFFFFF", image="le")
define slm = Character('Schlam', friendship=0, color="#FFFFFF", image="shlam")
