# Declare characters used by this game.
define sze = Character('Sze', color="#FCFCFC", image="arthur")
define rin = Character('Rina', color="#007408", image="serena")
define kok = Character('Willis', color="#666666", image="willis")
define flu = Character('FLUITSIE', color="#FFFFFF", image="fluitsma")
define rus = Character('Rusali', color="#FFFFFF", image="rusali")
define pra = Character('Pragash', color="#FFFFFF", image="pragash")
define dea = Character('Dean', color="#FFFFFF", image="dean")
define wil = Character('Will Yang', color="#ff0000", image="yang")
define tod = Character('Todd Treoir', color="#99ff99", image="todd")
define cha = Character('Chao', color="#FFFFFF", image="chao")
define mox = Character('MOXHAM', color="#FFFFFF", image="moxham")
define gra = Character('GRANT', color="#FFFFFF", image="grant")
define dik = Character('Richard', color="#FFFFFF", image="richard")
define drk = Character('Derek', color="#FFFFFF", image="derek")
define jit = Character('Gary', color="#FFFFFF", image="gary")
define lee = Character('Andrew', color="#FFFFFF", image="andrew")
define roy = Character('Roy', color="#FFFFFF", image="roy")
# jenkins
define but = Character('Aradhya', color="#FFFFFF", image="aradhya")
define dng = Character('Steven', color="#FFFFFF", image="steven")
define bil = Character('Bill the Cleaner', color="747D7D", image="bill")