label asszembly1shitstorm:
    "\"{b}WELL WELL WELL... what do we have here? {/b}\""
    "\"{b}Why are you outside of the assembly hall? {/b}\""
    "\"{b}And to think I finally have actionable proof ... the \"Untouchable\" Jitian Chen{/b}\""
    "..."
    "You barely remember the walk towards the Fountain Quad, at the head of a line of shame-faced students"
    "All you remember is Gary behind everyone, surrounded by 4 teachers"
    scene bg hallentrance
    with dissolve
    "..."
    "You are amazed that you can hear the drone of Moxham from outside the hall"
    "Yet, even more dreadful, the sense of impending doom, as the droning winds to an end, topped off with the final school song"
    "Moxham and her retinue gather outside the hall, engrossed in conversation, ignoring the line of the condemned"
    sze "...is she deliberately trying to make us scared shitless?"
    sze "..."
    sze "What horrible punishment is in line for us?"
    "You hear the restless talk of the rabble of students in the hall, as they begin filtering out"
    "With growing dread you realise Moxham's plan."
    mox "\"Ahem. Teachers, make sure no one leaves the fountain quad.\""
    mox "\"Look upon these fallen wretches. They thought they were so smart.\""
    mox "\"Better than the rest of us, with our silly assembly\""
    mox "\"These are the elite, the nobles, who would not dirty their auras with the presence of the rest of the school community\""
    "\"{i} Hah, look at those idiots. They shoulda just gone to assembly, like the rest of us {/i}\""
    "\"{i} Pathetic {/i}\""
    "\"{i} They get a participation medal for trying, I guess {/i}\""
    "\"{i} Better them than me! {/i}\""
    dik "\"Hmmm, do mine visual faculties belie me, or could that truly be Arthur Sze, kneeling yonder?\""
    kok "\"lulz, gg\""
    wil "\"So that's what he meant by \"had things to put into the locker\"...he'll be put into the locker, soon enough\""
    hou "\"wow, they're all scrubs\""
    rus "\"waow, I don't wanna be like them. They're legit trash\""
    mox "\"Unfortunately, as a result of their actions, recess has been shortened to 5 minutes.\""
    cha "\"wow, fking sze\""
    drk "\"trust sze to dog us\""
    mox "\"Fear not, for these aristocrats will be given a royal treatment.\""
    jump dead
# intro to wesley
# big detention for rest of the day